spring:
  data:
    cassandra:
      keyspace-name: main
      username: SbSPtAPznRqMjLsssSQZMZes
      password: zQaovaCMKZW66RsyrFniZlRKp20h0EdJ0GHWugzMF.Z0BNAdGwTJUzgeca0ExJAzG1-j9iJElKzMNC+IcWfzHCNzPcy_BMkdOUnQYp7PXlAfZuBoN6lgzTn1eBq7Gw3G
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra: 
  secure-connect-bundle: secure-connect-inbox-app.zip
  
astra.db: 
  id: 80eaad9b-ceae-4523-8ab7-5e1e0e1133b8-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:SbSPtAPznRqMjLsssSQZMZes:cc1acf7c4feb29dcbe5b5cc65fc4acf11bd959055e2b671b78a98c57cd98ff0c